Change to using FastAPI
OkeWoke/web_logger pull request #1
Opened 2022-10-26 09:04 UTC by NicoEvZ

2022-10-26 09:33 UTC, OkeWoke requested changes

2022-10-26 09:33 UTC, OkeWoke commented on web_logger/__init__.py
> +    return FileResponse("home.html")
This will just return the empty template html, not the rendered template I think.

2022-10-26 09:33 UTC, OkeWoke commented on web_logger/__init__.py
> +def ListDeviceIDs(device_id: int):
change func name

2022-10-26 09:50 UTC, OkeWoke commented on web_logger/__init__.py
> +app = FastAPI
app = FastAPI()

2022-10-26 09:50 UTC, OkeWoke commented on web_logger/__init__.py
> +app = FastAPI
```suggestion
app = FastAPI()

```

2022-10-26 09:51 UTC, OkeWoke commented on web_logger/__init__.py
> +def ListDeviceIDs(device_id: int):
```suggestion
def ListDeviceDims(device_id: int):

```

2022-10-26 09:57 UTC, OkeWoke commented on web_logger/__init__.py
> +    return FileResponse("home.html")
Have a look a this:
https://fastapi.tiangolo.com/advanced/templates/

2022-10-29 03:32 UTC, NicoEvZ commented
Changes have been made, please review.

2022-11-09 09:22 UTC, merged